#!/usr/bin/env python
#
# Fetal MRI Motion Correction plugin for ChRIS reloaded
#
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append( os.path.join(os.path.dirname(__file__), '../') )
from plugin import Plugin

class Fetal_Moco( Plugin ):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'Fetal MRI Motion Correction'
  Plugin.CATEGORY = 'Registration'
  Plugin.DESCRIPTION = 'Fetal MRI Motion Correction based on a method by Oxford University'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run( self, options ):

    cmd = '/chb/arch/Linux64/packages/fetal_moco/reconstruction '+options.output+'/out.nii 3 ' + options.Axial + ' ' + options.Sagittal + ' ' + options.Coronal + ' id id id'
    print cmd
    os.system(cmd)    


# ENTRYPOINT
if __name__ == "__main__":
  plugin = Fetal_Moco()
  plugin.add_parameter( 'Input', Plugin.IMAGE, '--axial', action='store', dest='Axial', help='the axial scan' )
  plugin.add_parameter( 'Input', Plugin.IMAGE, '--sagittal', action='store', dest='Sagittal', help='the sagittal scan' )
  plugin.add_parameter( 'Input', Plugin.IMAGE, '--coronal', action='store', dest='Coronal', help='the coronal scan' )
  plugin.add_parameter( 'Advanced', Plugin.INTEGER, '--iterations', action='store', default=9, dest='Iterations', help='Number of registration-reconstruction iterations.' )
  plugin.add_parameter( 'Advanced', Plugin.INTEGER, '--sigma', action='store', default=12, dest='Sigma', help='Stdev for bias field. [mm]' )
  plugin.add_parameter( 'Advanced', Plugin.DOUBLE, '--resolution', step=0.01, action='store', default=0.75, dest='Resolution', help='Isotropic resolution of the output volume.' )
  plugin.add_parameter( 'Advanced', Plugin.INTEGER, '--multires', action='store', default=3, dest='Multires', help='Multiresolution smoothing with given number of levels.' )
  plugin.add_parameter( 'Advanced', Plugin.INTEGER, '--average', action='store', default=700, dest='Average', help='Average intensity value for stacks.' )
  plugin.add_parameter( 'Advanced', Plugin.INTEGER, '--delta', action='store', default=150, dest='Delta', help='Parameter to define what is an edge.' )
  plugin.add_parameter( 'Advanced', Plugin.DOUBLE, '--lambda', step=0.02, action='store', default=0.02, dest='Lambda', help='Smoothing parameter.' )
  plugin.add_parameter( 'Advanced', Plugin.DOUBLE, '--lastIter', step=0.01, action='store', default=0.01, dest='LastIter', help='Smoothing parameter for last iteration.' )
  plugin.launch( sys.argv )
