#!/usr/bin/env python
#
# File Uploader plugin for ChRIS reloaded
# ______ _ _        _   _       _                 _           
# |  ___(_) |      | | | |     | |               | |          
# | |_   _| | ___  | | | |_ __ | | ___   __ _  __| | ___ _ __ 
# |  _| | | |/ _ \ | | | | '_ \| |/ _ \ / _` |/ _` |/ _ \ '__|
# | |   | | |  __/ | |_| | |_) | | (_) | (_| | (_| |  __/ |   
# \_|   |_|_|\___|  \___/| .__/|_|\___/ \__,_|\__,_|\___|_|   
#                        | |                                  
#                        |_|                                          |_|              
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../'))
from plugin import Plugin

import datetime as d

class File_Uploader(Plugin):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC Dev Team (dev@babyMRI.org)'
  Plugin.TITLE = 'File Uploader'
  Plugin.CATEGORY = 'System'
  Plugin.DESCRIPTION = '''
  File uploader documentation
  '''

  Plugin.DOCUMENTATION = 'https://github.com/FNNDSC/chrisreloaded/wiki/Plugin-file-uploader'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.3'

  def run(self, options):
    current_dir = os.path.dirname(os.path.abspath(__file__))
    
    print Plugin.TITLE
    print Plugin.VERSION

    # set permissions of output to 775
    os.chmod(options.output, '775')
        
# ENTRYPOINT
if __name__ == "__main__":
  plugin = File_Uploader()
  
  # this is an interactive plugin
  plugin.interactive = True
  # no cluster job monitoring to mark a feed instantly as done
  plugin.status = 100
  
  # define the parameters
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--listseries', action='store', dest='LIST_SERIES', help='Series to be downloaded: "study_uid,series_uid study_uid,series_uid, etc."')
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--feedid', action='store', default="{FEED_ID}", dest='FEED_ID', help='Feed ID')
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--userid', action='store', default="{USER_ID}", dest='USER_ID', help='User ID')
  plugin.launch(sys.argv)
