#!/usr/bin/env python
#
# CHRIS Push plugin for ChRIS reloaded
#       _           _                          _
#      | |         (_)                        | |
#  ____| |__   ____ _  ___    ____  _   _  ___| |__
# / ___)  _ \ / ___) |/___)  |  _ \| | | |/___)  _ \
#( (___| | | | |   | |___ |  | |_| | |_| |___ | | | |
# \____)_| |_|_|   |_(___/   |  __/|____/(___/|_| |_|
#                            |_|
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../'))
sys.path.append(os.path.join(os.path.dirname(__file__), '../../lib'))
from plugin import Plugin

from  _common import crun
from  _common import systemMisc as misc
import json
import datetime as d

class CHRIS_Push(Plugin):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'ChRIS_Push'
  Plugin.CATEGORY = 'system'
  Plugin.DESCRIPTION = 'Push data to a remote chris instance.'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run(self):
    options = self.options
    current_dir = os.path.dirname(os.path.abspath(__file__))

    print  d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> Start' + Plugin.TITLE + '...'

    print Plugin.TITLE
    print Plugin.VERSION

    #####
    #
    # MUST RUN AS CHRIS
    # CHRIS MUST HAVE ACCESS TO TARGET FILE
    #
    #####

    # we expect directory as input
    options.DIR = self.validate('directory', options.DIR);

    # is target valid?
    print "-- Remote information: ---"

    command = current_dir + "/scripts/getInfo.php -r " + options.REMOTE;

    localShell = crun.crun()
    localShell.echo(False)
    localShell.echoStdOut(False)
    localShell.echoStdErr(False)
    localShell.detach(False)
    localShell.waitForChild(True)

    print '- local ssh -'
    print command

    localShell(command)

    json_data = localShell.stdout()
    data = json.loads(json_data)

    print "Configured host = %s" % data['sshhost']
    print "Configured port = %s" % data['sshport']
    print data['src']

    if len(options.HOST) and len(options.PORT):
      options.SSHDEST  = True
    else:
      options.SSHDEST  = False

    if not options.SSHDEST:
      options.HOST = data['sshost']
      options.PORT = data['sshport']
    else:
      print('SSHDEST override detected...')

    print "Actual sshhost = %s" % options.HOST
    print "Actual sshport = %s" % options.PORT


    # get path of tmp and plugin dirs on remote server
    print "-- Remote configuration: ---"

    command = data['src'] + "/plugins/chris_push/scripts/getInfo.php -f " + data['src'] + '/config.inc.php -t -p';

    remoteShell = crun.crun()
    remoteShell._str_remoteHost = options.SSHHOST;
    remoteShell._str_remotePort = options.SSHPORt;
    remoteShell._str_remoteUser = 'chris';
    remoteShell._b_sshDo = True;
    remoteShell.echo(False)
    remoteShell.echoStdOut(False)
    remoteShell.echoStdErr(False)
    remoteShell.detach(False)
    remoteShell.waitForChild(True)

    print '- remote ssh -'
    print command

    remoteShell(command)

    json_data2 = remoteShell.stdout()
    data2 = json.loads(json_data2)

    print data2['tmp']
    print data2['plugin']

    # ZIP it!
    # ZIP plugin to current diri
    print "-- Go Zip plugin: ---"

    command = current_dir + "/../zip/zip --input " + options.DIR + " --output " + options.output

    print '- local ssh -'
    print command

    localShell(command)

    #
    # SCP it to tmp!
    print "-- SCP zip file to remote tmp: ---"

    command = "scp -P " +  options.SSHPORT + " " + options.output + "*.zip chris@" + options.SSHHOST  + ":"   + data2['tmp']

    print '- local ssh -'
    print command

    localShell(command)

    #
    # MAIL it!
    print "-- Email zip file link to remote user: ---"
    zipfile = ''
    for file in os.listdir(options.output):
      fileName, fileExtension = os.path.splitext(file)
      if fileExtension == ".zip":
        zipfile = file
        break

    command = data2['plugin'] + "/chris_push/scripts/emailUsr.php -u " + options.USERNAME + ' -z ' + data2['tmp'] + '/' + zipfile;

    print '- remote ssh -'
    print command

    remoteShell(command)

    print  d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> Finish...'

# ENTRYPOINT
if __name__ == "__main__":
  plugin = CHRIS_Push()
  plugin.add_parameter('Parameters', Plugin.IMAGE, '--directory', action='store', dest='DIR', help='Directory to be pushed')
  plugin.add_parameter('Parameters', Plugin.COMBOBOX, '--remote', values=['MGH', 'BCH'], action='store', default='MGH', dest='REMOTE', help='Remote CHRIS instance')
  plugin.add_parameter('Parameters', Plugin.STRING, '--user', action='store', default="username", dest='USERNAME', help='Recipient')

  plugin.add_parameter('Advanced (Network)', Plugin.STRING, '--host', action='store', default='', dest='HOST', help='Override host')
  plugin.add_parameter('Advanced (Network)', Plugin.STRING, '--port', action='store', default='', dest='PORT', help='Override port')

  plugin.launch()
