#!/usr/bin/env python
#
#       __ _ _     ______                                 
#     / _(_) |    | ___ \                                
#    | |_ _| | ___| |_/ /_ __ _____      _____  ___ _ __ 
#    |  _| | |/ _ \ ___ \ '__/ _ \ \ /\ / / __|/ _ \ '__|
#    | | | | |  __/ |_/ / | | (_) \ V  V /\__ \  __/ |   
#    |_| |_|_|\___\____/|_|  \___/ \_/\_/ |___/\___|_|   
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append( os.path.join(os.path.dirname(__file__), '../') )
from plugin import Plugin

class FileBrowser( Plugin ):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'FileBrowser'
  Plugin.CATEGORY = 'System'
  Plugin.DESCRIPTION = 'Generate a file/directory browser on given path'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run( self, options ):

    current_dir = os.path.dirname(os.path.abspath(__file__))
    os.system('ln -s %s %s' % (options.DIR, options.output))

# ENTRYPOINT
if __name__ == "__main__":
  plugin = FileBrowser()
  plugin.add_parameter( 'Input', Plugin.STRING, '--dir', action='store', dest='DIR', help='directory to browse' )
  plugin.launch( sys.argv )
