#!/usr/bin/env python
# _           _ _                            _     _ 
#| |         | | |                          | |   | |
#| | _   ____| | | ___     _ _ _  ___   ____| | _ | |
#| || \ / _  ) | |/ _ \   | | | |/ _ \ / ___) |/ || |
#| | | ( (/ /| | | |_| |  | | | | |_| | |   | ( (_| |
#|_| |_|\____)_|_|\___/    \____|\___/|_|   |_|\____|
#                                                    
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys, time

sys.path.append( os.path.join(os.path.dirname(__file__), '../') )
from plugin import Plugin

class Viewer(Plugin):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'Image Viewer Interactive Plugin'
  Plugin.CATEGORY = 'Visualization'
  Plugin.DESCRIPTION = 'Look at your data'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run(self):
      sys.path.append( os.path.join(os.path.dirname(__file__), 'libs/pydicom-0.9.8/dicom') )
      import dicom, json

      options = self.options

      extension = ['dcm']

      filesDirectory = 'files'
      filesDirectoryFullPath = os.path.join(options.output, filesDirectory)
      if not os.path.exists(filesDirectoryFullPath):
        os.makedirs(filesDirectoryFullPath)

      indexedData = {}

      targets = []
      index = 0
      for root, dirs, files in os.walk(options.DIRECTORY, topdown=False, followlinks=True):
        for fileName in files:
          if fileName.endswith(extension[0]):
            # read file
            ds = dicom.read_file(os.path.join(root, fileName))
            # index file
            if not ds.PatientID in indexedData:
              indexedData[ds.PatientID] = {}

            if not ds.StudyInstanceUID in indexedData[ds.PatientID]:
              indexedData[ds.PatientID][ds.StudyInstanceUID] = {}

            if not ds.SeriesInstanceUID in indexedData[ds.PatientID][ds.StudyInstanceUID]:
              indexedData[ds.PatientID][ds.StudyInstanceUID][ds.SeriesInstanceUID] = {}


            # print indexedData
            if not ds.SOPInstanceUID in indexedData[ds.PatientID][ds.StudyInstanceUID][ds.SeriesInstanceUID]:
              newRelativeName = os.path.join(filesDirectory, fileName + '-' + str(index))
              indexedData[ds.PatientID][ds.StudyInstanceUID][ds.SeriesInstanceUID][ds.SOPInstanceUID] = newRelativeName

              if not os.path.islink(os.path.join(options.output, newRelativeName)):
                os.symlink(os.path.join(root, fileName), os.path.join(options.output, newRelativeName))

              index += 1

      path = os.path.join(options.output, 'db.json')
      f = open(path,'w')
      f.write(json.dumps(indexedData))
      f.close()

# ENTRYPOINT
if __name__ == "__main__":
  plugin = Viewer()

  # this in an interactive plugin
  plugin.interactive = True

  plugin.add_parameter('Directory', Plugin.STRING, '--directory', action='store', dest='DIRECTORY', default='/neuro/users/chris/users/chris.test/data/dicom', help='Directory to be visualized')
  plugin.add_parameter('FeedID', Plugin.STRING, '--feedid', action='store', dest='FEEDID', default='', help='Feed ID to be viewed')

  plugin.launch()
