#!/usr/bin/env python
#
#                                                            _           
# FREESURFER RECON ALL
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append( os.path.join(os.path.dirname(__file__), '../') )
from plugin import Plugin

class recon_all( Plugin ):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'Freesurfer Recon-All'
  Plugin.CATEGORY = 'Freesurfer'
  Plugin.DESCRIPTION = 'Reconstruct a brain using Freesurfer'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run( self, options ):

    current_dir = os.path.dirname(os.path.abspath(__file__))
    
    # grab the first dicom input file
    firstDicomFile = os.listdir(options.MRI)[0]
    
    # launch recon-all
    cmd = 'cd ' + options.output +';' + current_dir + '/reconall.wrapper -subject Freesurfer -i ' + os.path.join(options.MRI, firstDicomFile) + ' -all'
    print cmd
    os.system(cmd)

# ENTRYPOINT
if __name__ == "__main__":
  plugin = recon_all()
  plugin.add_parameter( 'Input', Plugin.IMAGE, '--mri', action='store', dest='MRI', help='the mri scan to reconstruct' )
  plugin.launch( sys.argv )
