#!/usr/bin/env python
#
# Fetal MRI Motion Correction plugin for ChRIS reloaded
#
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append( os.path.join(os.path.dirname(__file__), '../') )
from plugin import Plugin

class Fetal_Moco( Plugin ):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'Fetal MRI Motion Correction'
  Plugin.CATEGORY = 'Registration'
  Plugin.DESCRIPTION = 'Fetal MRI Motion Correction based on a method by Oxford University'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run( self, options ):
    # do whatever
    print 'running moco'

# ENTRYPOINT
if __name__ == "__main__":
  plugin = Fetal_Moco()
  plugin.add_parameter( Plugin.IMAGE, '--t1_axial', action='store', dest='T1_axial', help='the axial T1 scan' )
  plugin.add_parameter( Plugin.IMAGE, '--t1_sagittal', action='store', dest='T1_sagittal', help='the sagittal T1 scan' )
  plugin.add_parameter( Plugin.IMAGE, '--t1_coronal', action='store', dest='T1_coronal', help='the coronal T1 scan' )
  plugin.launch( sys.argv )
