#!/usr/bin/env python
#
# Search patient plugin for ChRIS reloaded
#
#                         _                   _   _            _   
# ___  ___  __ _ _ __ ___| |__    _ __   __ _| |_(_) ___ _ __ | |_ 
#/ __|/ _ \/ _` | '__/ __| '_ \  | '_ \ / _` | __| |/ _ \ '_ \| __|
#\__ \  __/ (_| | | | (__| | | | | |_) | (_| | |_| |  __/ | | | |_ 
#|___/\___|\__,_|_|  \___|_| |_| | .__/ \__,_|\__|_|\___|_| |_|\__|
#                                |_|                               
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../'))
from plugin import Plugin

import datetime as d

class search_patient(Plugin):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'Search Patient'
  Plugin.CATEGORY = 'Search'
  Plugin.DESCRIPTION = 'Search for a patient in the Database'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run(self, options):
    current_dir = os.path.dirname(os.path.abspath(__file__))
    
    print Plugin.TITLE
    print Plugin.VERSION

    # preprocess!!
    print '======================================='
    print  d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> Start DB search...'
    search_command = current_dir + "/search_patient.php"
    #output directory
    search_command += " -o " + options.output
    if options.NAME:
      #name
      search_command += " -n " + options.NAME
    if options.DOB:
      #dob
      search_command += " -d " + options.DOB
    if options.ID:
      #uid=MRN
      search_command += " -i " + options.ID
    if options.SEX:
      #sex
      search_command += " -s " + options.SEX
      
    print 'command:'
    print search_command
    search_output = os.system(search_command)
    print 'output:'
    print search_output
    
    # evaluate pre_processing step
    # should return 0, if not, an issue occured, do not go to the next step
    if search_output == 0:
        print d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> DB search: SUCCESS'
        print 'EXIT search plugin NOW'
        print '(see search.log for more information)'
    else:
        print d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> DB search: FAILURE'
        print 'EXIT search plugin NOW'
        print '(see pre_process.log for more information)'
        return
        

# ENTRYPOINT
if __name__ == "__main__":
  plugin = search_patient()
  plugin.add_parameter('Input', Plugin.STRING, '--name', action='store', default='', dest='NAME', help='Name of the patient')
  plugin.add_parameter('Input', Plugin.STRING, '--dob', action='store', default='', dest='DOB', help='Date Of Birth of the patient')
  plugin.add_parameter('Input', Plugin.STRING, '--id', action='store', default='', dest='ID', help='UID of the patient')
  plugin.add_parameter('Input', Plugin.STRING, '--sex', action='store', default='', dest='SEX', help='Sex of the patient')
  plugin.launch(sys.argv)
