#!/usr/bin/env python
#
# Pacman plugin for ChRIS reloaded
#                                        
# _ __   __ _  ___ _ __ ___   __ _ _ __  
#| '_ \ / _` |/ __| '_ ` _ \ / _` | '_ \ 
#| |_) | (_| | (__| | | | | | (_| | | | |
#| .__/ \__,_|\___|_| |_| |_|\__,_|_| |_|
#|_|                                     
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#
# Adapted from https://github.com/daleharvey/pacman
#

# import the plugin.py superclass
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../'))
from plugin import Plugin

import datetime as d

class Pacman(Plugin):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org) based on https://github.com/daleharvey/pacman work'
  Plugin.TITLE = 'Pacman'
  Plugin.CATEGORY = 'Others'
  Plugin.DESCRIPTION = 'Port HTML5 pacman to chris as an example of interactive plugin integration'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.2'

  def run(self, options):
          print 'No CLI actions, I am a pure interactive plugin'
      

        
# ENTRYPOINT
if __name__ == "__main__":
  plugin = Pacman()
  
  # this is an interactive plugin
  plugin.interactive = True
  
  # define the parameters
  plugin.launch(sys.argv)
