#!/usr/bin/env python
#
#
#                      _ _ 
#                     (_) |
#      _ __ ___   __ _ _| |
#     | '_ ` _ \ / _` | | |
#     | | | | | | (_| | | |
#     |_| |_| |_|\__,_|_|_|
#                      
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append( os.path.join(os.path.dirname(__file__), '../') )
from plugin import Plugin

import datetime
import C_mail


class Mail( Plugin ):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'Mail'
  Plugin.CATEGORY = 'System'
  Plugin.DESCRIPTION = 'Send a quick email'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run( self, options ):

    CMail = C_mail.C_mail()

    current_dir = os.path.dirname(os.path.abspath(__file__))
    now = datetime.datetime.now()
    print options
    if options.output :
      f = open('%s/mail.log' % options.output, 'w')
      f.write("to: %s\n" % options.To)
      f.write("from: %s\n" % _str_sender)
      f.write("subject: %s\n" % options.Subject)
      f.write("date: %s" % now.strftime("%Y-%m-%d %H:%M"))
      f.write("\n")
      f.write("----\n")
      f.write("\n")
      f.write(options.Body)
      f.write("\n")
      f.write("----\n")
      f.close()
    CMail.mstr_SMTPserver = "localhost"
    CMail.send(to=options.To.split(','), subject=options.Subject, body=options.Body, sender=options.From)

# ENTRYPOINT
if __name__ == "__main__":
  _str_sender = "chris@chris.tch.harvard.edu"
  plugin = Mail()
  plugin.add_parameter( 'To', Plugin.STRING, '--to', action='store', dest='To', help='recipient' )
  plugin.add_parameter( 'From', Plugin.STRING, '--from', action='store', dest='From', help='sender', default=_str_sender )
  plugin.add_parameter( 'Subject', Plugin.STRING, '--subj', action='store', dest='Subject', help='subject' )
  plugin.add_parameter( 'Message', Plugin.STRING, '--msg', default='Email body', action='store', dest='Body', help='email body' )
  plugin.status = 100 # no cluster job monitoring to mark a feed instantly as done
  plugin.launch( sys.argv )
