#!/usr/bin/env python
# _           _ _                            _     _ 
#| |         | | |                          | |   | |
#| | _   ____| | | ___     _ _ _  ___   ____| | _ | |
#| || \ / _  ) | |/ _ \   | | | |/ _ \ / ___) |/ || |
#| | | ( (/ /| | | |_| |  | | | | |_| | |   | ( (_| |
#|_| |_|\____)_|_|\___/    \____|\___/|_|   |_|\____|
#                                                    
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys, time
sys.path.append( os.path.join(os.path.dirname(__file__), '../') )
from plugin import Plugin

class hello_world_interactive( Plugin ):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'Hello World Interactive Plugin'
  Plugin.CATEGORY = 'Tutorial'
  Plugin.DESCRIPTION = 'Present main ChRIS interactive plugin functionnalities'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run( self, options ):
      print 'I am sleeping 10s!'
      time.sleep(10)
      print 'I am done sleeping!'

# ENTRYPOINT
if __name__ == "__main__":
  plugin = hello_world_interactive()

  # this in an interactive plugin
  plugin.interactive = True
  
  # parameters passed from the ui
  plugin.add_parameter('name', Plugin.STRING, '--name', action='store', dest='NAME', help='Your name')
  
  plugin.launch( sys.argv )
