#!/usr/bin/env python
#
# PACS pull plugin for ChRIS reloaded
#
#  _ __   __ _  ___ ___   _ __  _   _| | |
# | '_ \ / _` |/ __/ __| | '_ \| | | | | |
# | |_) | (_| | (__\__ \ | |_) | |_| | | |
# | .__/ \__,_|\___|___/ | .__/ \__,_|_|_|
# |_|                    |_|              
#
#
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../'))
from plugin import Plugin

# import subprocess
import subprocess
# import logging
import logging

class PACS_Pull(Plugin):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'PACS_pull'
  Plugin.CATEGORY = 'PACS'
  Plugin.DESCRIPTION = 'Pull data from your PACS'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run(self, options):
    logging.basicConfig(filename=options.output + 'pacs_pull.log', level=logging.DEBUG, format='%(asctime)s %(message)s')

    logging.debug('running pacs pull...')
    logging.debug('parsing args...')
    logging.debug('MRN: ' + options.MRN)
    current_dir = os.path.dirname(os.path.abspath(__file__))
    
    # preprocess!!
    logging.debug('pre_processing...')
    command = current_dir + "/pre_process.php -u " + options.USER_ID + " -f " + options.FEED_ID + " -m " + options.MRN + " -s " + options.SERVER_IP + " -p " + options.SERVER_PORT + " -a " + options.USER_AET
    os.system(command)

    # and process!!
    logging.debug('processing...')
    process_command = current_dir + "/process.php" + " -m " + options.MRN + " -s " + options.SERVER_IP + " -p " + options.SERVER_PORT + " -a " + options.USER_AET
    process_output = os.system(process_command)
    logging.debug(process_output)
    
    # postprocess
    # look in tmp directory if any directory contains what we are looking for
    # if data is there, move it around in a good way


# ENTRYPOINT
if __name__ == "__main__":
  plugin = PACS_Pull()
  plugin.add_parameter('Input', Plugin.STRING, '--mrn', action='store', default='4524909', dest='MRN', help='MRN to be pulled')
  plugin.add_parameter('Advanced', Plugin.STRING, '--aet', action='store', default='FNNDSC-CHRISDEV', dest='USER_AET', help='User AETitle')
  plugin.add_parameter('Advanced', Plugin.STRING, '--serverip', action='store', default='134.174.12.21', dest='SERVER_IP', help='Server IP')
  plugin.add_parameter('Advanced', Plugin.STRING, '--serverport', action='store', default='104', dest='SERVER_PORT', help='Server Port')
  plugin.add_parameter('Advanced', Plugin.STRING, '--dcmtk', action='store', default='/usr/bin', dest='DCMTK', help='DCMTK base directory')
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--feedid', action='store', default="{FEED_ID}", dest='FEED_ID', help='Feed ID')
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--userid', action='store', default="{USER_ID}", dest='USER_ID', help='User ID')
  plugin.launch(sys.argv)
