#!/usr/bin/env python
#
# Fyborg plugin for ChRIS reloaded
#
#   ___         __
# .'  _|.--.--.|  |--..-----..----..-----.
# |   _||  |  ||  _  ||  _  ||   _||  _  |
# |__|  |___  ||_____||_____||__|  |___  |
#       |_____|                    |_____|
#
# THE ULTIMATE SCALAR MAPPING FRAMEWORK FOR TRACKVIS (.TRK) FILES
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append( os.path.join( os.path.dirname( __file__ ), '../' ) )
from plugin import Plugin

class Fyborg( Plugin ):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'Fyborg'
  Plugin.CATEGORY = 'Diffusion'
  Plugin.DESCRIPTION = 'Fyborg - the ultimate Scalar Mapping Framework for TrackVis (.trk) Files'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run( self, options ):
    # copy input and dti to one temp folder
    # and run fyborg on it
    # import tempfile, shutil, subprocess
    # tempdir = tempfile.mkdtemp( 'fy', 'borg', '/chb/tmp' )
    # shutil.copytree( options.Freesurfer, tempdir + '/T1' )
    # shutil.copytree( options.Tractography, tempdir + '/DTI' )
    cmd = ''
    cmd += '/chb/arch/scripts/fyconn.py -i ' + options.Connectome + ' -o ' + options.output + ' -r ' + options.Radius + ' --overwrite --verbose'
    # sp = subprocess.Popen( ["/bin/bash", "-i", "-c", cmd], stdout=sys.stdout )
    # sp.communicate()
    os.system( cmd );

# ENTRYPOINT
if __name__ == "__main__":
  plugin = Fyborg()
  plugin.add_parameter( 'Input', Plugin.IMAGE, '--connectome', action='store', dest='Connectome', help='the Connectome folder' )
  plugin.add_parameter( 'Advanced', Plugin.INTEGER, '--radius', action='store', default=3, dest='Radius', help='the look-around Radius' )
  plugin.launch( sys.argv )
