#!/usr/bin/env python
#
# Fyborg plugin for ChRIS reloaded
#
#   ___         __
# .'  _|.--.--.|  |--..-----..----..-----.
# |   _||  |  ||  _  ||  _  ||   _||  _  |
# |__|  |___  ||_____||_____||__|  |___  |
#       |_____|                    |_____|
#
# THE ULTIMATE SCALAR MAPPING FRAMEWORK FOR TRACKVIS (.TRK) FILES
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append( os.path.join( os.path.dirname( __file__ ), '../' ) )
from plugin import Plugin

scripts_dir = os.environ['ENV_FYBORG_DIR']
sys.path.append( scripts_dir )
sys.path.append( os.path.join( scripts_dir, 'fyborg' ) )
sys.path.append( os.path.join( scripts_dir, 'fyborg', '_common' ) )
try:
  from fyconn import *
except:
  pass


class Fyborg( Plugin ):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'Fyborg'
  Plugin.CATEGORY = 'Diffusion'
  Plugin.DESCRIPTION = 'Fyborg - the ultimate Scalar Mapping Framework for TrackVis (.trk) Files'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run( self, options ):
    # copy input and dti to one temp folder
    # and run fyborg on it
    
    # we expect directories as input
    options.Freesurfer = self.validate('directory', options.Freesurfer);
    options.DTI = self.validate('directory', options.DTI);
    
    import tempfile, shutil, subprocess
    tempdir = tempfile.mkdtemp( 'fy', 'borg', os.environ['ENV_TMP_DIR'] )
    shutil.copytree( options.Freesurfer, tempdir + '/T1' )
    shutil.copytree( options.DTI, tempdir + '/DTI' )
    # cmd = ''
    # cmd += '/chb/arch/scripts/fyconn.py -i ' + tempdir + ' -o ' + options.output + ' -r ' + options.Radius + ' --overwrite --verbose'
    # sp = subprocess.Popen( ["/bin/bash", "-i", "-c", cmd], stdout=sys.stdout )
    # sp.communicate()
    # os.system( cmd );
    logic = FyborgLogic()
    logic.run( tempdir, options.output, int( options.Radius ), str( options.MinLength ) + " " + str( options.MaxLength ), -1, False, True )
    # clean up
    shutil.rmtree( tempdir )


# ENTRYPOINT
if __name__ == "__main__":
  plugin = Fyborg()
  plugin.add_parameter( 'Input', Plugin.IMAGE, '--freesurfer', action='store', dest='Freesurfer', help='the Freesurfer reconstruction' )
  plugin.add_parameter( 'Input', Plugin.IMAGE, '--dti', action='store', dest='DTI', help='the DTI reconstruction' )
  plugin.add_parameter( 'Advanced', Plugin.INTEGER, '--radius', action='store', default=3, dest='Radius', help='the look-around Radius' )
  plugin.add_parameter( 'Advanced', Plugin.INTEGER, '--min_length', action='store', default=20, dest='MinLength', help='the min. length in mm for length-filtering' )
  plugin.add_parameter( 'Advanced', Plugin.INTEGER, '--max_length', action='store', default=200, dest='MaxLength', help='the max. length in mm for length-filtering' )
  plugin.launch( sys.argv )
