#!/usr/bin/env python
#
# PACS pull plugin for ChRIS reloaded
#
#  _ __   __ _  ___ ___   _ __  _   _| | |
# | '_ \ / _` |/ __/ __| | '_ \| | | | | |
# | |_) | (_| | (__\__ \ | |_) | |_| | | |
# | .__/ \__,_|\___|___/ | .__/ \__,_|_|_|
# |_|                    |_|              
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../'))
from plugin import Plugin

import datetime as d

class PACS_Pull(Plugin):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'PACS_pull'
  Plugin.CATEGORY = 'PACS'
  Plugin.DESCRIPTION = 'Pull data from your PACS to our ChRIS server.'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.2'

  def run(self, options):
    current_dir = os.path.dirname(os.path.abspath(__file__))
    
    print Plugin.TITLE
    print Plugin.VERSION
    # if "MRN" provided, split on "white spaces" and loop through them
    if options.MRN:
      list_mrn = options.MRN.strip().split(" ");
      for mrn in list_mrn:
        print mrn
        # process!!
        print '======================================='
        print  d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> Start processing...'
        command = current_dir + "/process.php -u " + options.USER_ID + " -f " + options.FEED_ID + " -m " + mrn + " -s " + options.SERVER_IP + " -p " + options.SERVER_PORT + " -a " + options.USER_AET + " -y MR " + " -o " + options.output
        print 'command:'
        print command
        output = os.system(command)
        print 'output:'
        print output
    
        # evaluate processing step
        if output == 0:
          print d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> Processing: SUCCESS'
          print '(see process.log for more information)'
        else:
          print d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> Processing: FAILURE'
          print 'EXIT pacs_pull plugin NOW'
          print '(see process.log for more information)'
    # else if "LIST_SERIES" provided, loop through them 
    elif options.LIST_SERIES:
      print options.LIST_SERIES
      list_series = options.LIST_SERIES.strip().split(" ");
      for pair in list_series:
        study, series = pair.split(",");
        # process!!
        print '======================================='
        print  d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> Start processing...'
        command = current_dir + "/process.php -u " + options.USER_ID + " -f " + options.FEED_ID + " -s " + options.SERVER_IP + " -p " + options.SERVER_PORT + " -a " + options.USER_AET + " -o " + options.output + " -d " + study + " -e " + series 
        print 'command:'
        print command
        output = os.system(command)
        print 'output:'
        print output
    
        # evaluate processing step
        if output == 0:
          print d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> Processing: SUCCESS'
          print '(see process.log for more information)'
        else:
          print d.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ' ---> Processing: FAILURE'
          print 'EXIT pacs_pull plugin NOW'
          print '(see process.log for more information)'
      

        
# ENTRYPOINT
if __name__ == "__main__":
  plugin = PACS_Pull()
  
  # this is an interactive plugin
  plugin.interactive = True
      
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--mrn', action='store', dest='MRN', help='MRN to be pulled (mrn1 mrn2 mrn3 etc.)')
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--aet', action='store', default='AETITLE', dest='USER_AET', help='User AETitle')
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--serverip', action='store', default='134.174.12.21', dest='SERVER_IP', help='Server IP')
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--serverport', action='store', default='104', dest='SERVER_PORT', help='Server Port')
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--listseries', action='store', dest='LIST_SERIES', help='Series to be downloaded: "study_uid,series_uid study_uid,series_uid, etc."')
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--feedid', action='store', default="{FEED_ID}", dest='FEED_ID', help='Feed ID')
  plugin.add_parameter('HIDDEN', Plugin.STRING, '--userid', action='store', default="{USER_ID}", dest='USER_ID', help='User ID')
  plugin.launch(sys.argv)
