#!/usr/bin/env python
#
#              _
#             | |      
#  _ __   ___ | |_ ___ 
# | '_ \ / _ \| __/ _ \
# | | | | (_) | ||  __/
# |_| |_|\___/ \__\___|
#
# (c) 2012 Fetal-Neonatal Neuroimaging & Developmental Science Center
#                   Boston Children's Hospital
#
#              http://childrenshospital.org/FNNDSC/
#                        dev@babyMRI.org
#

# import the plugin.py superclass
import os, sys
sys.path.append( os.path.join(os.path.dirname(__file__), '../') )
from plugin import Plugin

class FileBrowser( Plugin ):
  '''
  '''
  Plugin.AUTHORS = 'FNNDSC (dev@babyMRI.org)'
  Plugin.TITLE = 'Note'
  Plugin.CATEGORY = 'System'
  Plugin.DESCRIPTION = 'Simply HTML note'
  Plugin.DOCUMENTATION = 'http://wiki'
  Plugin.LICENSE = 'Opensource (MIT)'
  Plugin.VERSION = '0.1'

  def run( self, options ):

    f = open('%s/index.html' % options.output, 'w')
    f.write("""<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">""")
    f.write("\n\n\n")
    f.write("<head><body>")
    f.write("\n")
    f.write("%s" % options.noteHtml)
    f.write("\n")
    f.write("</boby></head>")
    f.close()
    
    # link the created index.html to ../index.html
    os.link('%s/index.html' % options.output, '%s/../index.html' % options.output)

# ENTRYPOINT
if __name__ == "__main__":
  plugin = FileBrowser()
  plugin.add_parameter( 'Note', Plugin.STRING, '--textBox', default='Enter some html here.', action='store', dest='noteHtml', help='add some html notes' )
  plugin.status = 100 # no cluster job monitoring to mark a feed instantly as done
  plugin.launch( sys.argv )
